name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      should_run_backend: ${{ steps.filter.outputs.backend == 'true' }}
      should_run_frontend: ${{ steps.filter.outputs.frontend == 'true' }}

    steps:
      - uses: actions/checkout@v4

      - name: Check changed paths
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  build-and-test-backend:
    needs: [changes]
    if: needs.changes.outputs.should_run_backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v5

      - name: Build backend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          load: true
          tags: |
            ${{ vars.BACKEND_ECR_REGISTRY }}:test

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: '${{ vars.BACKEND_ECR_REGISTRY }}:test'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

  build-and-test-frontend:
    needs: [changes]
    if: needs.changes.outputs.should_run_frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v5

      - name: Build frontend Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          load: true
          tags: |
            ${{ vars.FRONTEND_ECR_REGISTRY }}:test

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: '${{ vars.FRONTEND_ECR_REGISTRY }}:test'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

  CI-status:
    needs: [changes, build-and-test-backend, build-and-test-frontend]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Report CI result
        run: |
          BACKEND_RESULT="${{ needs.build-and-test-backend.result }}"
          FRONTEND_RESULT="${{ needs.build-and-test-frontend.result }}"

          if [[ "$BACKEND_RESULT" == "failure" || "$BACKEND_RESULT" == "cancelled" ]]; then
            echo "CI failed: backend"
            exit 1
          fi

          if [[ "$FRONTEND_RESULT" == "failure" || "$FRONTEND_RESULT" == "cancelled" ]]; then
            echo "CI failed: frontend"
            exit 1
          fi

          echo "CI passed"